name: Build and Release C++ 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup C++ environment
      uses: actions/setup-cpp@v3  # Corrected action name
      with:
        cpp-version: 'gnu-latest' 

    - name: Build with Make
      run: make

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ matrix.os == 'windows-latest' && 'your_program.exe' || 'your_program' }} 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
