name: Build and Upload Binaries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3



    - name: Run Makefile
      run: |
        make
      shell: bash

    - name: Upload binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-binary
        path: |
          build/mbox2eml # Replace with the actual path or pattern of your binaries
